apps:
  - script: 'serve'
    name: 'front-ever'
    watch: true
    env:
      PM2_SERVE_PATH: './front'
      PM2_SERVE_PORT: 8074
      PM2_SERVE_SPA: 'true'
      PM2_SERVE_HOMEPAGE: '/index.html'
      # PM2_SERVE_BASIC_AUTH: 'true'
      # PM2_SERVE_BASIC_AUTH_USERNAME: ${EVER_DEMO_USERNAME}
      # PM2_SERVE_BASIC_AUTH_PASSWORD: ${EVER_DEMO_PASSWORD}
